### ISSUE TITLE
Mixtrack Pro3 Debug Help

### ISSUE THREAD

**Issue by NotYourAverageAl** [henrizo-configs/mixxx#1]
Hi @henrizo-configs just wondering if you still have your controller.

I'm trying to debug an issue with the mixxx 2.3 beta. The tempo slider is having a few issues
1. There is a delay when moving the physical tempo slider compared to the software slider. I cant predict where the slider will end up basically.
2. the gui stutters when moving the controller tempo slider

if you are still using your controller can you confirm of you are having any of these issues.
I like your additions to the mapping and thought to go back to using the controller

**Comment by matheushsouza** [comment]
Hello, @NotYourAverageAl! :)

I'm really sorry for replying with a delay of 7 days. Haven't had my most peaceful days lately.

So... I've just compiled and installed mixxx 2.3 beta on my machine --- since I was using the stable 2.2.4-4 version, from Arch Linux's community repo --- and, unfortunately, I **couldn't reproduce any of your described issues**. 

I don't remember ever having any problems with the tempo sliders, specifically, but I do remember facing a similar problem with the GUI, when using the Deere theme. The GUI suttered on whatever button, knob, or slider I moved. I don't remember the version --- 2.1, maybe ---, and It solved itself fast after an update, so I don't have any insights about what it could be.

Moreover, I don't believe it has to do with my config. When I had this stuttering problem, It happened with the default Mixtrack Pro3 config as well.

Did you find anything relevant about it in these last 7 days?

**Comment by NotYourAverageAl** [comment]
No worries @matheushsouza, hope you are doing ok.

Yeah I have no idea what's causing this & I have not been able to figure it out. Could be windows 10, Mixxx 2.2.4 works fine though, so does Serato, so its not the controller either. its definitely not your config, it happens on the default config as well. See video of the issue. https://user-images.githubusercontent.com/24758479/111292242-16c59600-869c-11eb-9412-7ecf8f53b080.mp4

I'll keep working on it and raise this in the forums. thought you might have had an insight since you played around with the mapping. Thanks for responding

I want to try and push your update "Effects are focused with TAP + FX and activated with FX, unlike the original file, which inverts these controls" upstream. It's more intuitive than the default :)

**Comment by matheushsouza** [comment]
Yeah... Really odd behaviour you've got there, unfortunately.

I hope you'll be able to fix it soon. I'll keep one eye on it as well and, if I find anything relevant or experience the same issues, I'll reach out to you so we can solve it together.

I'm glad you like my patches :)

Best regards!
